### ISSUE TITLE
Liveness probes run too often in the example deployment

### ISSUE THREAD

**Issue by Adiqq** [rabbitmq/rabbitmq-peer-discovery-k8s#28]
Hi,

There are probes in example:
```
        livenessProbe:
          exec:
            command: ["rabbitmqctl", "status"]
          initialDelaySeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          exec:
            command: ["rabbitmqctl", "status"]
          initialDelaySeconds: 10
          timeoutSeconds: 10
```

In our cluster, these commands were executed every 10 seconds which led to enormous CPU usage (70%) for rabbitmq cluster without any workload.
It would be nice to mention that this command is so heavyweight and provide some sane `periodSeconds` for example.
