### ISSUE TITLE
Read-only file system

### ISSUE THREAD

**Issue by Sermanes** [rabbitmq/rabbitmq-peer-discovery-k8s#37]
Hi!

When I try to create my rabbitmq in my cluster, I get the following config-map error.

`sed: can't create temp file '/etc/rabbitmq/rabbitmq.confXXXXXX': Read-only file system`

What can I do to solve the problem?

**Comment by lukebakken** [comment]
You are probably running into an issue like kubernetes/kubernetes#62099. I recommend searching the issues in that project for the string `read only file system`

**Comment by michaelklishin** [comment]
This plugin does not control any properties of the filesystem. This is [Kubernetes] mailing list material.

**Comment by Sermanes** [comment]
I found a solution:

```
    initContainers:
      - name: configmap-copy
        image: busybox
        command: ['/bin/sh', '-c', 'cp /etc/rabbitmq/files/* /etc/rabbitmq/']
        volumeMounts:
        - name: config-volume
          mountPath: /etc/rabbitmq/files
        - name: config
          mountPath: /etc/rabbitmq
      volumes:
      - name: config
        emptyDir: {}
      - name: config-volume
        configMap:
          name: rabbitmq-config
          items:
          - key: rabbitmq.conf
            path: rabbitmq.conf
          - key: enabled_plugins
            path: enabled_plugins
```

If someone have the same problem in kubernetes.

Thanks @lukebakken  @michaelklishin !
