### ISSUE TITLE
Why my rabbitmq node cannot discovery?

### ISSUE THREAD

**Issue by penglongli** [rabbitmq/rabbitmq-peer-discovery-k8s#40]
## Conf
**Openshift 3.9 Env**
rbac.yml
``` yml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rabbitmq
  namespace: {{ namespace }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: endpoint-reader
  namespace: {{ namespace }}
rules:
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: endpoint-reader
  namespace: {{ namespace }}
subjects:
- kind: ServiceAccount
  name: rabbitmq
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: endpoint-reader
```

statefulset.yml
```
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: rabbitmq
  namespace: {{ namespace }}
spec:
  serviceName: rabbitmq
  replicas: 3
  volumeClaimTemplates:
    - metadata:
        name: rabbitmq-data
      spec:
        storageClassName: {{ sc_name }}
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      serviceAccountName: rabbitmq
      terminationGracePeriodSeconds: 10
      containers:
      - name: rabbitmq-k8s
        image: rabbitmq:3.7
        volumeMounts:
          - name: config-volume
            mountPath: /etc/rabbitmq
          - name: rabbitmq-data
            mountPath: /var/lib/rabbitmq
          - name: rabbitmq-logs
            mountPath: /var/log/rabbitmq
        ports:
          - name: http
            protocol: TCP
            containerPort: 15672
          - name: amqp
            protocol: TCP
            containerPort: 5672
        livenessProbe:
          exec:
            command: ["rabbitmqctl", "status"]
          initialDelaySeconds: 20
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          exec:
            command: ["rabbitmqctl", "status"]
          initialDelaySeconds: 20
          periodSeconds: 30
          timeoutSeconds: 10
        imagePullPolicy: IfNotPresent
        subdomain: mq
        env:
          - name: MY_POD_HOSTNAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
                #fieldPath: status.podIP
          - name: RABBITMQ_USE_LONGNAME
            value: "true"
          - name: K8S_SERVICE_NAME
            value: "rabbitmq"
          # See a note on cluster_formation.k8s.address_type in the config file section
          - name: RABBITMQ_NODENAME
            value: "rabbit@$(MY_POD_HOSTNAME).rabbitmq.{{ namespace }}.svc.cluster.local"
          - name: RABBITMQ_ERLANG_COOKIE
            value: "mycookie"
          - name: K8S_HOSTNAME_SUFFIX
            value: ".rabbitmq.{{ namespace }}.svc.cluster.local"
      volumes:
        - name: rabbitmq-logs
          emptyDir: {}
        - name: config-volume
          configMap:
            name: rabbitmq-configmap
            items:
            - key: rabbitmq_conf
              path: rabbitmq.conf
            - key: enabled_plugins
              path: enabled_plugins
            - key: definitions
              path: definitions.json
```

configmaps with file
```
---------- enable_plugins
[rabbitmq_management,rabbitmq_peer_discovery_k8s].

--------- rabbitmq.conf
log.console = true
log.console.level = debug
cluster_formation.peer_discovery_backend  = rabbit_peer_discovery_k8s
cluster_formation.k8s.host = kubernetes.default.svc.cluster.local
cluster_formation.k8s.address_type = hostname
cluster_formation.node_cleanup.interval = 30
cluster_formation.node_cleanup.only_log_warning = true
cluster_partition_handling = autoheal
queue_master_locator=min-masters
loopback_users.guest = false
management.load_definitions = /etc/rabbitmq/definitions.json

--------- definitions.json
{
  "vhosts": [
    {"name": "/"}
  ],
  "users": [
    {"name": "guest", "password": "guest", "tags": "administrator"}
  ],
  "permissions": [
    {"user": "guest", "vhost": "/", "configure": ".*", "write": ".*", "read": ".*"},
  ],
  "policies":[
    {"vhost": "/", "name": "ha-all", "pattern": ".*", "apply-to": "all", "definition": {"ha-mode":"all","ha-sync-mode":"automatic"}, "priority":0},
  ]
}
```

## Question

I start 3 replicas, and pvc bound normal. Every node is normal. But they cannot discovery each other.
```
---------- rabbitmq-0
$ rabbitmqctl cluster_status
Cluster status of node rabbit@rabbitmq-0.rabbitmq.test-rabbitmq.svc.cluster.local ...
[{nodes,[{disc,['rabbit@rabbitmq-0.rabbitmq.test-rabbitmq.svc.cluster.local']}]},
 {running_nodes,['rabbit@rabbitmq-0.rabbitmq.test-rabbitmq.svc.cluster.local']},
 {cluster_name,<<"rabbit@rabbitmq-0.rabbitmq.test-rabbitmq.svc.cluster.local">>},
 {partitions,[]},
 {alarms,[{'rabbit@rabbitmq-0.rabbitmq.test-rabbitmq.svc.cluster.local',[]}]}]

-------- rabbitmq-1
Cluster status of node rabbit@rabbitmq-1.rabbitmq.test-rabbitmq.svc.cluster.local ...
[{nodes,[{disc,['rabbit@rabbitmq-1.rabbitmq.test-rabbitmq.svc.cluster.local']}]},
 {running_nodes,['rabbit@rabbitmq-1.rabbitmq.test-rabbitmq.svc.cluster.local']},
 {cluster_name,<<"rabbit@lg-dev-web">>},
 {partitions,[]},
 {alarms,[{'rabbit@rabbitmq-1.rabbitmq.test-rabbitmq.svc.cluster.local',[]}]}]

-------- rabbitmq-2
Cluster status of node rabbit@rabbitmq-2.rabbitmq.test-rabbitmq.svc.cluster.local ...
[{nodes,[{disc,['rabbit@rabbitmq-2.rabbitmq.test-rabbitmq.svc.cluster.local']}]},
 {running_nodes,['rabbit@rabbitmq-2.rabbitmq.test-rabbitmq.svc.cluster.local']},
 {cluster_name,<<"rabbit@rabbitmq-2.rabbitmq.test-rabbitmq.svc.cluster.local">>},
 {partitions,[]},
 {alarms,[{'rabbit@rabbitmq-2.rabbitmq.test-rabbitmq.svc.cluster.local',[]}]}]
```
