### ISSUE TITLE
Minikube example is arguably incomplete

### ISSUE THREAD

**Issue by wizquest-labs** [rabbitmq/rabbitmq-peer-discovery-k8s#51]
Many users have posted issues regarding service discovery not happening, even on google group.

[#40](https://github.com/rabbitmq/rabbitmq-peer-discovery-k8s/issues/40)

The Example File for StateFul Sets, does not provide a spec for DNS resolution, which is supposed to happen inside the deployed pods.

In order to facilitate this, we must create an additional service of type ClusterIP or edit an existing one.

Additional Service looks like :

```yaml
kind: Service
apiVersion: v1
metadata:
  namespace: default
  name: rabbitmq-ext
  labels:
    app: rabbitmq
spec:
  ports:
    - name: http
      protocol: TCP
      port: 15672
      targetPort: 15672
      nodePort: 31672
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: 5672
      nodePort: 30672
  selector:
    app: rabbitmq
```

The correct config must look like the one below.

[updated_rabbitmq_statefulsets.txt](https://github.com/rabbitmq/rabbitmq-peer-discovery-k8s/files/3642501/updated_rabbitmq_statefulsets.txt)
